name: network_font
description: Help you easily uses font from network.
version: 0.0.1
author: Kithe Raker <kithe.raker@gmail.com>
homepage: https://github.com/kithe-raker/network_font

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Get user's local path
  path_provider: ^2.0.1

  # Make get request to network font
  http: ^0.13.1

  # Store data to user's local
  hive: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
